/*
 * ABAP Data Dictionary (DDIC) Definitions
 * Tables: ZSC_PLANT, ZSC_STOCK, ZSC_SUPPLIER, ZSC_ACTIONS
 */

/*
TABL ZSC_PLANT
  MANDT     : CLNT(3)   KEY
  PLANT_ID  : CHAR(4)   KEY
  NAME      : CHAR(40)
  LATITUDE  : DEC(9,6)
  LONGITUDE : DEC(9,6)
  REGION    : CHAR(10)

TABL ZSC_STOCK
  MANDT     : CLNT(3)   KEY
  PLANT_ID  : CHAR(4)   KEY
  MATNR     : CHAR(18)  KEY
  QTY_ON_HAND : QUAN(13,3)
  SAFETY_STK  : QUAN(13,3)
  DAILY_DEMAND: QUAN(13,3)

TABL ZSC_SUPPLIER
  MANDT       : CLNT(3) KEY
  LIFNR       : CHAR(10) KEY
  NAME        : CHAR(40)
  LEAD_TIME   : INT4
  RELIABILITY : DEC(3,2)
  IS_BLOCKED  : CHAR(1)
*/
